Repository Hyeon9mak/HCP_2020, pull requests merged in 2020-11, with the labels that each got.

#22 Create 2020-11-07-회의기록.md
  회의기록/2020-11-07-회의기록.md
Labels: develop, documentation

#28 Create 2020-11-17-회의기록.md
  회의기록/2020-11-17-회의기록.md
Labels: documentation

#30 수정 했습니다
  Map.txt
  소스.c
Labels: develop

#31 hyeon9_branch 내용 master로 병합
  Map.txt
  소스.c
  소스코드/소스.c
Labels: develop

#33 오류, 화면 깜박임 제거, 지름길 색 추가
  Map.txt
  소스.c
Labels: develop

#34 Update 소스.c
  소스.c
Labels: develop
